version: '3.9'

services:
  db:
    image: postgres:15
    container_name: finance-app-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
      PGCLIENTENCODING: UTF8
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-app-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/finance
      SMTP_EMAIL: www.eser808@gmail.com
      SMTP_PASSWORD: juzbtsspqcllgcin
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      PYTHONIOENCODING: utf-8
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "8000:8000"
    command: ["./wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  pgdata:
